/*
 * Copyright (C) Ascensio System SIA, 2009-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation, together with the
 * additional terms provided in the LICENSE file.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
 * details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA by email at info@onlyoffice.com
 * or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
 * LV-1050, Latvia, European Union.
 *
 * The interactive user interfaces in modified versions of the Program
 * are required to display Appropriate Legal Notices in accordance with
 * Section 5 of the GNU AGPL version 3.
 *
 * No trademark rights are granted under this License.
 *
 * All non-code elements of the Product, including illustrations,
 * icon sets, and technical writing content, are licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License:
 * https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * This license applies only to such non-code elements and does not
 * modify or replace the licensing terms applicable to the Program's
 * source code, which remains licensed under the GNU Affero General
 * Public License v3.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */
#ifndef _WIN32
#include "WinColor.h"

unsigned int GetSysColor(const int nIndex)
{
	// get color values from any windows theme
	// http://msdn.microsoft.com/en-us/library/windows/desktop/ms724371(v=vs.85).aspx
	// generated by test from: \TeamlabOffice\trunk\ServerComponents\Test\Applications\Tokenize_Test
	//***************** GetSysColor values begin (Win7 x64) *****************
    unsigned int nValue = 0x0;
	//***************** GetSysColor values begin (Win7 x64) *****************
	switch (nIndex) {
	case COLOR_3DDKSHADOW: nValue = 0x696969; break;
	case COLOR_3DFACE: nValue = 0xf0f0f0; break;
	case COLOR_3DHIGHLIGHT: nValue = 0xffffff; break;
		// case COLOR_3DHILIGHT: nValue = 0xffffff; break; // is COLOR_3DHIGHLIGHT
	case COLOR_3DLIGHT: nValue = 0xe3e3e3; break;
	case COLOR_3DSHADOW: nValue = 0xa0a0a0; break;
	case COLOR_ACTIVEBORDER: nValue = 0xb4b4b4; break;
	case COLOR_ACTIVECAPTION: nValue = 0xd1b499; break;
	case COLOR_APPWORKSPACE: nValue = 0xababab; break;
	case COLOR_BACKGROUND: nValue = 0x0; break;
		// case COLOR_BTNFACE: nValue = 0xf0f0f0; break; // is COLOR_3DFACE
		// case COLOR_BTNHIGHLIGHT: nValue = 0xffffff; break; // is COLOR_3DHIGHLIGHT
		// case COLOR_BTNHILIGHT: nValue = 0xffffff; break; // is COLOR_3DHIGHLIGHT
		// case COLOR_BTNSHADOW: nValue = 0xa0a0a0; break; // is COLOR_3DSHADOW
	case COLOR_BTNTEXT: nValue = 0x0; break;
	case COLOR_CAPTIONTEXT: nValue = 0x0; break;
		// case COLOR_DESKTOP: nValue = 0x0; break; // is COLOR_BACKGROUND
	case COLOR_GRADIENTACTIVECAPTION: nValue = 0xead1b9; break;
	case COLOR_GRADIENTINACTIVECAPTION: nValue = 0xf2e4d7; break;
	case COLOR_GRAYTEXT: nValue = 0x6d6d6d; break;
	case COLOR_HIGHLIGHT: nValue = 0xff9933; break;
	case COLOR_HIGHLIGHTTEXT: nValue = 0xffffff; break;
	case COLOR_HOTLIGHT: nValue = 0xcc6600; break;
	case COLOR_INACTIVEBORDER: nValue = 0xfcf7f4; break;
	case COLOR_INACTIVECAPTION: nValue = 0xdbcdbf; break;
	case COLOR_INACTIVECAPTIONTEXT: nValue = 0x544e43; break;
	case COLOR_INFOBK: nValue = 0xe1ffff; break;
	case COLOR_INFOTEXT: nValue = 0x0; break;
	case COLOR_MENU: nValue = 0xf0f0f0; break;
	case COLOR_MENUHILIGHT: nValue = 0xff9933; break;
	case COLOR_MENUBAR: nValue = 0xf0f0f0; break;
	case COLOR_MENUTEXT: nValue = 0x0; break;
	case COLOR_SCROLLBAR: nValue = 0xc8c8c8; break;
	case COLOR_WINDOW: nValue = 0xffffff; break;
	case COLOR_WINDOWFRAME: nValue = 0x646464; break;
	case COLOR_WINDOWTEXT: nValue = 0x0; break;
	default: nValue = 0x0; break;
	} // switch (nIndex)
	//***************** GetSysColor values end *****************
	return nValue;
}

#endif
