/*
 * Copyright (C) Ascensio System SIA, 2009-2026
 *
 * This program is a free software product. You can redistribute it and/or
 * modify it under the terms of the GNU Affero General Public License (AGPL)
 * version 3 as published by the Free Software Foundation, together with the
 * additional terms provided in the LICENSE file.
 *
 * This program is distributed WITHOUT ANY WARRANTY; without even the implied
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. For
 * details, see the GNU AGPL at: https://www.gnu.org/licenses/agpl-3.0.html
 *
 * You can contact Ascensio System SIA by email at info@onlyoffice.com
 * or by postal mail at 20A-6 Ernesta Birznieka-Upisha Street, Riga,
 * LV-1050, Latvia, European Union.
 *
 * The interactive user interfaces in modified versions of the Program
 * are required to display Appropriate Legal Notices in accordance with
 * Section 5 of the GNU AGPL version 3.
 *
 * No trademark rights are granted under this License.
 *
 * All non-code elements of the Product, including illustrations,
 * icon sets, and technical writing content, are licensed under the
 * Creative Commons Attribution-ShareAlike 4.0 International License:
 * https://creativecommons.org/licenses/by-sa/4.0/legalcode
 *
 * This license applies only to such non-code elements and does not
 * modify or replace the licensing terms applicable to the Program's
 * source code, which remains licensed under the GNU Affero General
 * Public License v3.
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class docbuilder_CDocBuilder */

#ifndef _Included_docbuilder_CDocBuilder
#define _Included_docbuilder_CDocBuilder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilder_c_1Create
  (JNIEnv *, jclass);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1Destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_OpenFile
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1OpenFile
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_CreateFileByType
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1CreateFileByType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_CreateFileByExtension
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1CreateFileByExtension
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SetTmpFolder
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1SetTmpFolder
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SaveFileByType
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1SaveFileByType
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SaveFileByTypeWithParams
 * Signature: (JILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1SaveFileByTypeWithParams
  (JNIEnv *, jclass, jlong, jint, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SaveFileByExtension
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1SaveFileByExtension
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SaveFileByExtensionWithParams
 * Signature: (JLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_docbuilder_CDocBuilder_c_1SaveFileByExtensionWithParams
  (JNIEnv *, jclass, jlong, jstring, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_CloseFile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1CloseFile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_ExecuteCommand
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1ExecuteCommand
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_ExecuteCommandWithRetValue
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1ExecuteCommandWithRetValue
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Run
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1Run
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_RunText
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1RunText
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_SetProperty
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1SetProperty
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_WriteData
 * Signature: (JLjava/lang/String;Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1WriteData
  (JNIEnv *, jclass, jlong, jstring, jstring, jboolean);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_IsSaveWithDoctrendererMode
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_docbuilder_CDocBuilder_c_1IsSaveWithDoctrendererMode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_GetVersion
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_docbuilder_CDocBuilder_c_1GetVersion
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_GetContext
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilder_c_1GetContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_GetContextWithEnterParam
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_docbuilder_CDocBuilder_c_1GetContextWithEnterParam
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1Initialize
  (JNIEnv *, jclass);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_InitializeWithDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1InitializeWithDirectory
  (JNIEnv *, jclass, jstring);

/*
 * Class:     docbuilder_CDocBuilder
 * Method:    c_Dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_docbuilder_CDocBuilder_c_1Dispose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
